name: Run Adactin Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 🔧 Install Firefox (just to be sure it's latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: 🛠️ Run Tests with Maven
        run: xvfb-run mvn clean test

      - name: 📁 Upload Extent Reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: target/*.html